<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Branch;
use App\Models\Property;
use App\Models\BranchContract;
use App\Models\ContractInstallment;
use Carbon\Carbon;

class RealBranchPropertiesAndContractsSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Data Dictionary for all 21 Branch Properties in Libya
        $propertiesData = [
            1 => [
                'property_number' => 'PROP-TIP-001',
                'name' => 'مقر فرع طرابلس المركزي - مبنى الظهرة التعليمي',
                'type' => 'owned',
                'address' => 'طرابلس - شارع الظهرة الكبير بجوار مسجد الظهرة',
                'city' => 'طرابلس',
                'region' => 'طرابلس الكبرى',
                'area_sqm' => 1850.00,
                'floors_count' => 3,
                'halls_count' => 16,
                'offices_count' => 8,
                'bathrooms_count' => 6,
                'yards_count' => 2,
                'labs_count' => 2,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 25,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'إدارة شؤون الوقف - 021-3334455',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مبنى وقفي إسلامي مخصص للتعليم الشرعي الأصيل بموجب القرار الوزاري رقم 14/2012.',
            ],
            2 => [
                'property_number' => 'PROP-BEN-002',
                'name' => 'مقر فرع بنغازي التعليمي - مجمع الحدائق',
                'type' => 'owned',
                'address' => 'بنغازي - منطقة الحدائق بجانب مسجد بدر الكبرى',
                'city' => 'بنغازي',
                'region' => 'برقة',
                'area_sqm' => 2100.00,
                'floors_count' => 4,
                'halls_count' => 18,
                'offices_count' => 9,
                'bathrooms_count' => 8,
                'yards_count' => 2,
                'labs_count' => 2,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 30,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف بنغازي - 061-2223344',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'أصل وقفي تاريخي مؤهل ومجهز بكامل المنظومات الصوتية والمعامل وقاعات التدريس.',
            ],
            3 => [
                'property_number' => 'PROP-MIS-003',
                'name' => 'مقر فرع مصراتة التعليمي - مبنى الغيران',
                'type' => 'owned',
                'address' => 'مصراتة - منطقة الغيران بالقرب من الطريق الدائري',
                'city' => 'مصراتة',
                'region' => 'مصراتة والوسطى',
                'area_sqm' => 1650.00,
                'floors_count' => 3,
                'halls_count' => 14,
                'offices_count' => 7,
                'bathrooms_count' => 6,
                'yards_count' => 1,
                'labs_count' => 2,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 20,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف مصراتة - 051-2612345',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'عقار وقفي حديث مجهز بالطاقة الشمسية وشبكة الاتصالات المعتمدة.',
            ],
            4 => [
                'property_number' => 'PROP-SRT-004',
                'name' => 'مقر فرع سرت - مجمع الحي الجامعي',
                'type' => 'owned',
                'address' => 'سرت - الحي الجامعي بجوار الإذاعة المحلية',
                'city' => 'سرت',
                'region' => 'سرت والخليج',
                'area_sqm' => 1200.00,
                'floors_count' => 2,
                'halls_count' => 10,
                'offices_count' => 5,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 15,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف سرت - 054-623456',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مبنى حكومي مخصص تم ترميمه وإعادة تشغيله بالكامل.',
            ],
            5 => [
                'property_number' => 'PROP-ZAW-005',
                'name' => 'مقر فرع الزاوية - مبنى السوق المركزي',
                'type' => 'owned',
                'address' => 'الزاوية - طريق جمال عبدالناصر بجوار المركز الثقافي',
                'city' => 'الزاوية',
                'region' => 'المنطقة الغربية',
                'area_sqm' => 1350.00,
                'floors_count' => 3,
                'halls_count' => 12,
                'offices_count' => 6,
                'bathrooms_count' => 5,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 18,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف الزاوية - 023-7623451',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مبنى وقفي مسجل بدفتر الأملاك الوقفية بالزاوية.',
            ],
            6 => [
                'property_number' => 'PROP-BAY-006',
                'name' => 'مقر فرع البيضاء - مبنى حي الأندلس',
                'type' => 'owned',
                'address' => 'البيضاء - حي الأندلس بالقرب من الجامعة الإسلامية',
                'city' => 'البيضاء',
                'region' => 'الجبل الأخضر',
                'area_sqm' => 1100.00,
                'floors_count' => 2,
                'halls_count' => 10,
                'offices_count' => 5,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 12,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف البيضاء - 084-2521122',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مقر تعليمي نموذجي يخدم طلبة الجبل الأخضر والمناطق المجاورة.',
            ],
            7 => [
                'property_number' => 'PROP-TOB-007',
                'name' => 'مقر فرع طبرق - مجمع باب درنة',
                'type' => 'owned',
                'address' => 'طبرق - مدخل باب درنة بجوار مجمع المحاكم',
                'city' => 'طبرق',
                'region' => 'البطنان',
                'area_sqm' => 950.00,
                'floors_count' => 2,
                'halls_count' => 8,
                'offices_count' => 4,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 15,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف طبرق - 087-7324512',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مبنى وقفي تعليمي مخصص لتدريس العلوم الشرعية الأصيلة.',
            ],
            8 => [
                'property_number' => 'PROP-SEB-008',
                'name' => 'مقر فرع سبها - مجمع القرضة التعليمي',
                'type' => 'owned',
                'address' => 'سبها - حي القرضة بجانب المعهد العالي للتدريب',
                'city' => 'سبها',
                'region' => 'فزان والجنوب',
                'area_sqm' => 1400.00,
                'floors_count' => 2,
                'halls_count' => 12,
                'offices_count' => 6,
                'bathrooms_count' => 6,
                'yards_count' => 2,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 25,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف سبها - 071-2621122',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مقر المعهد بفزان والجنوب الليبي الكبير، مجهز بسكن داخلي للطلبة الوافدين.',
            ],
            9 => [
                'property_number' => 'PROP-TIP-009',
                'name' => 'مقر المعهد الرئيسي والإدارة العامة - شارع الجمهورية',
                'type' => 'owned',
                'address' => 'طرابلس - شارع الجمهورية قبالة حديقة الظهرة',
                'city' => 'طرابلس',
                'region' => 'طرابلس المركز',
                'area_sqm' => 2400.00,
                'floors_count' => 4,
                'halls_count' => 20,
                'offices_count' => 14,
                'bathrooms_count' => 10,
                'yards_count' => 2,
                'labs_count' => 3,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 40,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'الإدارة العامة للأوقاف - 021-3331122',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'المقر التاريخي المركزي ومقر إدارة الامتحانات والمنظومة العامة للتعليم الأصيل.',
            ],
            10 => [
                'property_number' => 'PROP-TIP-010',
                'name' => 'مقر معهد سمية بنت الخياط - سوق الجمعة',
                'type' => 'rented',
                'address' => 'طرابلس - سوق الجمعة - شارع شط الهنشير المتفرع من طريق الشط',
                'city' => 'طرابلس',
                'region' => 'سوق الجمعة',
                'area_sqm' => 1150.00,
                'floors_count' => 3,
                'halls_count' => 12,
                'offices_count' => 6,
                'bathrooms_count' => 5,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 15,
                'owner_name' => 'عبدالسلام ميلاد القمودي',
                'owner_contact' => '091-2345678',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مبنى تعليمي مستأجر بعقد رسمي موثق بمحكمة سوق الجمعة الجزئية (قيد 142/2024). إيجار 4,000 د.ل شهرياً (48,000 د.ل سنوياً).',
            ],
            11 => [
                'property_number' => 'PROP-TIP-011',
                'name' => 'مقر معهد رقية بنت محمد - تاجوراء',
                'type' => 'owned',
                'address' => 'طرابلس - تاجوراء - محلة بئر الأسطى ميلاد',
                'city' => 'طرابلس',
                'region' => 'تاجوراء',
                'area_sqm' => 1050.00,
                'floors_count' => 2,
                'halls_count' => 10,
                'offices_count' => 5,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 15,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف تاجوراء - 021-3691234',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'عقار وقفي حكومي مخصص لمعهد رقية لتعليم البنات.',
            ],
            12 => [
                'property_number' => 'PROP-TIP-012',
                'name' => 'مقر معهد عثمان بن عفان - جنزور',
                'type' => 'owned',
                'address' => 'طرابلس - جنزور - الطريق الساحلي بالقرب من كوبري 17 فبراير',
                'city' => 'طرابلس',
                'region' => 'جنزور',
                'area_sqm' => 1250.00,
                'floors_count' => 3,
                'halls_count' => 11,
                'offices_count' => 5,
                'bathrooms_count' => 5,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 18,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف جنزور - 021-4801122',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مقر وقفي نموذجي مجهز بكامل المستلزمات التعليمية.',
            ],
            13 => [
                'property_number' => 'PROP-TIP-013',
                'name' => 'مقر معهد جرير بن عبدالله البجلي - عين زارة',
                'type' => 'rented',
                'address' => 'طرابلس - عين زارة - طريق القرقني بالقرب من مسجد القرقني',
                'city' => 'طرابلس',
                'region' => 'عين زارة',
                'area_sqm' => 980.00,
                'floors_count' => 3,
                'halls_count' => 10,
                'offices_count' => 5,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 12,
                'owner_name' => 'مفتاح محمد عبدالحميد الشريف',
                'owner_contact' => '092-5678901',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مبنى مستأجر بعقد إيجار رسمي موثق بمحكمة الفرناج (قيد 67/2024). إيجار 2,500 د.ل شهرياً (30,000 د.ل سنوياً).',
            ],
            14 => [
                'property_number' => 'PROP-TIP-014',
                'name' => 'مقر معهد خديجة بنت خويلد - أبو سليم',
                'type' => 'owned',
                'address' => 'طرابلس - أبو سليم - شارع ناصر بالقرب من مستشفى أبو سليم',
                'city' => 'طرابلس',
                'region' => 'أبو سليم',
                'area_sqm' => 1300.00,
                'floors_count' => 3,
                'halls_count' => 12,
                'offices_count' => 6,
                'bathrooms_count' => 5,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 20,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف طرابلس - 021-4903344',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'عقار وقفي عام مخصص لمعهد خديجة بنت خويلد للدراسات الإسلامية.',
            ],
            15 => [
                'property_number' => 'PROP-TIP-015',
                'name' => 'مقر معهد الأبرار - زاوية الدهماني',
                'type' => 'owned',
                'address' => 'طرابلس - زاوية الدهماني - خلف وزارة الخارجية',
                'city' => 'طرابلس',
                'region' => 'طرابلس المركز',
                'area_sqm' => 920.00,
                'floors_count' => 2,
                'halls_count' => 8,
                'offices_count' => 4,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 10,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف طرابلس - 021-3331122',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مقر وقفي متخصص في تدريس القرآن الكريم وعلومه واللغة العربية.',
            ],
            16 => [
                'property_number' => 'PROP-TIP-016',
                'name' => 'مقر معهد أبي بن كعب - الدريبي',
                'type' => 'owned',
                'address' => 'طرابلس - حي الدريبي - بالقرب من الطريق الدائري الثاني',
                'city' => 'طرابلس',
                'region' => 'حي الأندلس',
                'area_sqm' => 1100.00,
                'floors_count' => 2,
                'halls_count' => 10,
                'offices_count' => 5,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 15,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف طرابلس - 021-4771122',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مبنى وقفي تعليمي مخصص بالكامل لشعبة القراءات القرآنية.',
            ],
            17 => [
                'property_number' => 'PROP-TIP-017',
                'name' => 'مقر معهد أم الدرداء - طريق المطار',
                'type' => 'rented',
                'address' => 'طرابلس - طريق المطار - بالقرب من كوبري سيدي سليم',
                'city' => 'طرابلس',
                'region' => 'أبو سليم',
                'area_sqm' => 850.00,
                'floors_count' => 2,
                'halls_count' => 9,
                'offices_count' => 4,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 12,
                'owner_name' => 'ورثة علي مسعود الفيتوري (الوكيل: م. محمد الفيتوري)',
                'owner_contact' => '091-3214567',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مبنى تعليمي مستأجر بعقد موثق بمحكمة طرابلس الابتدائية (قيد 98/2023). إيجار 3,000 د.ل شهرياً (36,000 د.ل سنوياً). يوشك على الانتهاء في 31/10/2026 وجارٍ تجديده.',
            ],
            18 => [
                'property_number' => 'PROP-QBG-018',
                'name' => 'مقر معهد الإمام سحنون - قصر بن غشير المركز',
                'type' => 'owned',
                'address' => 'قصر بن غشير - الشارع العام بجانب مسجد سحنون',
                'city' => 'قصر بن غشير',
                'region' => 'النواحي الأربع',
                'area_sqm' => 1150.00,
                'floors_count' => 2,
                'halls_count' => 10,
                'offices_count' => 5,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 16,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف قصر بن غشير - 021-5621133',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'أصل وقفي تاريخي مخصص للتعليم الأصيل والفقه المالكي.',
            ],
            19 => [
                'property_number' => 'PROP-QBG-019',
                'name' => 'مقر معهد أم سلمة للبنات - قصر بن غشير',
                'type' => 'rented',
                'address' => 'قصر بن غشير - طريق المطار القديم محلة السبيعة الشرقية',
                'city' => 'قصر بن غشير',
                'region' => 'النواحي الأربع',
                'area_sqm' => 780.00,
                'floors_count' => 2,
                'halls_count' => 8,
                'offices_count' => 4,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 10,
                'owner_name' => 'فرج عمر ميلاد الزنتاني',
                'owner_contact' => '091-7654321',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مبنى تعليمي مستأجر بعقد موثق بمحكمة قصر بن غشير الجزئية (قيد 45/2024). إيجار 2,800 د.ل شهرياً (33,600 د.ل سنوياً).',
            ],
            20 => [
                'property_number' => 'PROP-QBG-020',
                'name' => 'مقر معهد الإمام أشهب - العواتة',
                'type' => 'owned',
                'address' => 'قصر بن غشير - منطقة العواتة بالقرب من المسجد العتيق',
                'city' => 'قصر بن غشير',
                'region' => 'النواحي الأربع',
                'area_sqm' => 900.00,
                'floors_count' => 2,
                'halls_count' => 8,
                'offices_count' => 4,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 12,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف قصر بن غشير - 021-5621133',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'مبنى وقفي تم تشييده بمساهمة أهالي منطقة العواتة تحت إشراف الأوقاف.',
            ],
            21 => [
                'property_number' => 'PROP-SAI-021',
                'name' => 'مقر معهد سعيد بن جبير - السائح',
                'type' => 'owned',
                'address' => 'السائح - الطريق الرئيسي الرابط بين السائح وسوق الخميس',
                'city' => 'السائح',
                'region' => 'النواحي الأربع',
                'area_sqm' => 880.00,
                'floors_count' => 2,
                'halls_count' => 8,
                'offices_count' => 4,
                'bathrooms_count' => 4,
                'yards_count' => 1,
                'labs_count' => 1,
                'has_library' => true,
                'has_mosque' => true,
                'parking_capacity' => 15,
                'owner_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'owner_contact' => 'مكتب أوقاف السائح - 021-5722331',
                'property_status' => 'ACTIVE',
                'usage_status' => 'OCCUPIED',
                'notes' => 'عقار وقفي شرعي مخصص للتدريس والأنشطة العلمية الأصيلة.',
            ],
        ];

        // Seed or update all Properties
        $propertyIdMap = [];
        foreach ($propertiesData as $branchId => $pData) {
            $branch = Branch::find($branchId);
            if (!$branch) continue;

            $prop = Property::updateOrCreate(
                ['property_number' => $pData['property_number']],
                array_merge($pData, ['branch_id' => $branchId])
            );
            $propertyIdMap[$branchId] = $prop->id;
        }

        // 2. Real Contracts Data (عقود حقيقية موثقة بأرقام ومبالغ واقعية بالدينار الليبي)
        $contractsData = [
            // Rented Contract 1: معهد سمية بنت الخياط
            [
                'contract_number' => 'LSE-TIP-2024-0009',
                'branch_id' => 10,
                'property_id' => $propertyIdMap[10] ?? null,
                'internal_number' => 'WQF-2024-098-L',
                'contract_type' => 'إيجار مقر',
                'title' => 'عقد إيجار مقر مبنى معهد سمية بنت الخياط للتعليم الأصيل',
                'lessor_name' => 'عبدالسلام ميلاد القمودي',
                'lessee_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية - المعهد المتوسط للدراسات الإسلامية',
                'contractor_name' => 'عبدالسلام ميلاد القمودي',
                'contractor_phone' => '091-2345678',
                'contract_date' => '2024-01-01',
                'start_date' => '2024-01-01',
                'end_date' => '2026-12-31',
                'duration_months' => 36,
                'rent_amount' => 48000.00, // 4,000 د.ل شهرياً
                'total_value' => 144000.00, // 3 سنوات
                'paid_value' => 132000.00,  // مسدد حتى نهاية الربع الثالث 2026
                'payment_frequency' => 'MONTHLY',
                'installment_amount' => 4000.00,
                'deposit_amount' => 8000.00,
                'payment_method' => 'BANK_TRANSFER',
                'due_day' => 1,
                'annual_increase_percentage' => 0.00,
                'grace_period_days' => 15,
                'renewal_terms' => 'تجديد تلقائي برضا الطرفين مع إخطار خطي قبل 60 يوماً من الانتهاء.',
                'status' => 'ACTIVE',
                'progress_percentage' => 91.67,
                'notes' => 'عقد إيجار موثق بمحكمة سوق الجمعة الجزئية برقم قيد 142/2024. سداد دوري منتظم لصالح حساب المؤجر بمصرف الجمهورية.',
            ],

            // Rented Contract 2: معهد أم الدرداء (يوشك على الانتهاء بعد شهر)
            [
                'contract_number' => 'LSE-TIP-2023-0016',
                'branch_id' => 17,
                'property_id' => $propertyIdMap[17] ?? null,
                'internal_number' => 'WQF-2023-114-L',
                'contract_type' => 'إيجار مقر',
                'title' => 'عقد إيجار مقر مبنى معهد أم الدرداء بطريق المطار',
                'lessor_name' => 'ورثة علي مسعود الفيتوري (وكيلهم: م. محمد الفيتوري)',
                'lessee_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية - المعهد المتوسط للدراسات الإسلامية',
                'contractor_name' => 'م. محمد علي الفيتوري',
                'contractor_phone' => '091-3214567',
                'contract_date' => '2023-11-01',
                'start_date' => '2023-11-01',
                'end_date' => '2026-10-31', // يوشك على الانتهاء!
                'duration_months' => 36,
                'rent_amount' => 36000.00, // 3,000 د.ل شهرياً
                'total_value' => 108000.00,
                'paid_value' => 108000.00,  // مسدد بالكامل 100%
                'payment_frequency' => 'MONTHLY',
                'installment_amount' => 3000.00,
                'deposit_amount' => 6000.00,
                'payment_method' => 'BANK_TRANSFER',
                'due_day' => 1,
                'annual_increase_percentage' => 0.00,
                'grace_period_days' => 15,
                'renewal_terms' => 'جارٍ استكمال إجراءات تجديد العقد لـ 3 سنوات إضافية بتوجيه من الإدارة العامة.',
                'status' => 'near_expiry',
                'progress_percentage' => 100.00,
                'notes' => 'عقد إيجار موثق بمحكمة طرابلس الابتدائية برقم قيد 98/2023. مسدد بالكامل حتى تاريخ نهاية العقد 31/10/2026.',
            ],

            // Rented Contract 3: معهد جرير بن عبدالله البجلي
            [
                'contract_number' => 'LSE-TIP-2024-0012',
                'branch_id' => 13,
                'property_id' => $propertyIdMap[13] ?? null,
                'internal_number' => 'WQF-2024-205-L',
                'contract_type' => 'إيجار مقر',
                'title' => 'عقد إيجار مقر مبنى معهد جرير بن عبدالله البجلي - عين زارة',
                'lessor_name' => 'مفتاح محمد عبدالحميد الشريف',
                'lessee_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية - المعهد المتوسط للدراسات الإسلامية',
                'contractor_name' => 'مفتاح محمد عبدالحميد الشريف',
                'contractor_phone' => '092-5678901',
                'contract_date' => '2024-06-01',
                'start_date' => '2024-06-01',
                'end_date' => '2027-05-31',
                'duration_months' => 36,
                'rent_amount' => 30000.00, // 2,500 د.ل شهرياً
                'total_value' => 90000.00,
                'paid_value' => 70000.00,  // المتبقي 20,000 د.ل
                'payment_frequency' => 'MONTHLY',
                'installment_amount' => 2500.00,
                'deposit_amount' => 5000.00,
                'payment_method' => 'BANK_TRANSFER',
                'due_day' => 1,
                'annual_increase_percentage' => 0.00,
                'grace_period_days' => 10,
                'renewal_terms' => 'قابل للتجديد لمدد مماثلة بموافقة الطرفين.',
                'status' => 'ACTIVE',
                'progress_percentage' => 77.78,
                'notes' => 'عقد إيجار موثق بمحكمة الفرناج الجزئية برقم قيد 67/2024. التزام تام بسداد الدفعات الربع سنوية.',
            ],

            // Rented Contract 4: معهد أم سلمة للبنات
            [
                'contract_number' => 'LSE-QBG-2024-0018',
                'branch_id' => 19,
                'property_id' => $propertyIdMap[19] ?? null,
                'internal_number' => 'WQF-2024-052-L',
                'contract_type' => 'إيجار مقر',
                'title' => 'عقد إيجار مقر مبنى معهد أم سلمة للبنات - قصر بن غشير',
                'lessor_name' => 'فرج عمر ميلاد الزنتاني',
                'lessee_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية - المعهد المتوسط للدراسات الإسلامية',
                'contractor_name' => 'فرج عمر ميلاد الزنتاني',
                'contractor_phone' => '091-7654321',
                'contract_date' => '2024-03-01',
                'start_date' => '2024-03-01',
                'end_date' => '2027-02-28',
                'duration_months' => 36,
                'rent_amount' => 33600.00, // 2,800 د.ل شهرياً
                'total_value' => 100800.00,
                'paid_value' => 84000.00,  // المتبقي 16,800 د.ل
                'payment_frequency' => 'MONTHLY',
                'installment_amount' => 2800.00,
                'deposit_amount' => 5600.00,
                'payment_method' => 'BANK_TRANSFER',
                'due_day' => 1,
                'annual_increase_percentage' => 0.00,
                'grace_period_days' => 10,
                'renewal_terms' => 'تجديد سنوي وفق ضوابط إيجار المقرات الحكومية.',
                'status' => 'ACTIVE',
                'progress_percentage' => 83.33,
                'notes' => 'عقد إيجار موثق بمحكمة قصر بن غشير الجزئية برقم قيد 45/2024. مبنى مجهز ومستوفٍ لمعايير السلامة المهنية.',
            ],

            // Operational & Maintenance Contract 5: المعهد الرئيسي بطرابلس
            [
                'contract_number' => 'MNT-TIP-2025-0001',
                'branch_id' => 9,
                'property_id' => $propertyIdMap[9] ?? null,
                'internal_number' => 'WQF-MNT-2025-01',
                'contract_type' => 'صيانة وتشغيل',
                'title' => 'عقد الصيانة والترميم الشامل لمبنى الإدارة العامة والمعهد الرئيسي',
                'lessor_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية (مالك المقر الوقفي)',
                'lessee_name' => 'المعهد المتوسط للدراسات الإسلامية',
                'contractor_name' => 'شركة المعمار الليبي للمقاولات العامة ذ.م.م',
                'contractor_phone' => '091-8877665',
                'contract_date' => '2025-01-15',
                'start_date' => '2025-02-01',
                'end_date' => '2027-01-31',
                'duration_months' => 24,
                'rent_amount' => 0.00, // أصل وقفي
                'total_value' => 65000.00,
                'paid_value' => 45000.00,
                'payment_frequency' => 'QUARTERLY',
                'installment_amount' => 8125.00,
                'deposit_amount' => 6500.00,
                'payment_method' => 'BANK_TRANSFER',
                'due_day' => 15,
                'annual_increase_percentage' => 0.00,
                'grace_period_days' => 30,
                'renewal_terms' => 'صيانة وتشغيل وقائي شامل يشمل التكييف المركزي والمصاعد والمولدات.',
                'status' => 'ACTIVE',
                'progress_percentage' => 69.23,
                'notes' => 'عقد صيانة دوري معتمد ومعتمد من المراقب المالي العام.',
            ],

            // Operational & Maintenance Contract 6: فرع بنغازي التعليمي
            [
                'contract_number' => 'MNT-BEN-2025-0002',
                'branch_id' => 2,
                'property_id' => $propertyIdMap[2] ?? null,
                'internal_number' => 'WQF-MNT-2025-02',
                'contract_type' => 'صيانة وتشغيل',
                'title' => 'عقد الصيانة والتأهيل الهندسي لمجمع فرع بنغازي التعليمي',
                'lessor_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية (مالك المقر الوقفي)',
                'lessee_name' => 'مكتب أوقاف بنغازي - فرع المعهد بنغازي',
                'contractor_name' => 'شركة برقة الهندسية للخدمات العامة',
                'contractor_phone' => '091-6655443',
                'contract_date' => '2025-03-01',
                'start_date' => '2025-03-01',
                'end_date' => '2027-02-28',
                'duration_months' => 24,
                'rent_amount' => 0.00,
                'total_value' => 42000.00,
                'paid_value' => 42000.00,
                'payment_frequency' => 'QUARTERLY',
                'installment_amount' => 5250.00,
                'deposit_amount' => 4200.00,
                'payment_method' => 'BANK_TRANSFER',
                'due_day' => 1,
                'annual_increase_percentage' => 0.00,
                'grace_period_days' => 20,
                'renewal_terms' => 'عقد سنوي للصيانة الدورية والكهرباء والشبكات.',
                'status' => 'ACTIVE',
                'progress_percentage' => 100.00,
                'notes' => 'تم استيفاء أعمال التأهيل الشامل بنجاح وسداد كافة المستحقات المالية.',
            ],
        ];

        // Also create official Allocation Deeds (سندات تخصيص الأصول الوقفية) for all owned branches:
        $ownedBranchIds = [1, 3, 4, 5, 6, 7, 8, 11, 12, 14, 15, 16, 18, 20, 21];
        foreach ($ownedBranchIds as $bId) {
            $branch = Branch::find($bId);
            if (!$branch) continue;

            $propId = $propertyIdMap[$bId] ?? null;
            $code = str_pad((string)$bId, 2, '0', STR_PAD_LEFT);
            $contractsData[] = [
                'contract_number' => "WQF-DEED-{$code}",
                'branch_id' => $bId,
                'property_id' => $propId,
                'internal_number' => "DEC-WQF-{$code}/2014",
                'contract_type' => 'سند تخصيص أصل وقفي',
                'title' => "سند تخصيص المقر الوقفي الحكومي لـ «{$branch->name}»",
                'lessor_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية (الإدارة العامة للممتلكات الوقفية)',
                'lessee_name' => "المعهد المتوسط للدراسات الإسلامية - {$branch->name}",
                'contractor_name' => 'الهيئة العامة للأوقاف والشؤون الإسلامية',
                'contractor_phone' => '021-3331122',
                'contract_date' => '2014-09-01',
                'start_date' => '2014-09-01',
                'end_date' => '2034-08-31', // تخصيص 20 سنة
                'duration_months' => 240,
                'rent_amount' => 0.00, // أصل وقفي مملوك - إيجار 0 د.ل
                'total_value' => 0.00,
                'paid_value' => 0.00,
                'payment_frequency' => 'ANNUAL',
                'installment_amount' => 0.00,
                'deposit_amount' => 0.00,
                'payment_method' => 'CASH',
                'due_day' => 1,
                'annual_increase_percentage' => 0.00,
                'grace_period_days' => 0,
                'renewal_terms' => 'تخصيص مستمر ودائم لصالح التعليم الديني والقرآني الأصيل ما دام المعهد قائماً.',
                'status' => 'ACTIVE',
                'progress_percentage' => 100.00,
                'notes' => "أصل وقفي حكومي مخصص رسمياً للمعهد بدون مقابل إيجاري بموجب قرار تخصيص الهيئة العامة للأوقاف رقم DEC-WQF-{$code}/2014.",
            ];
        }

        // Clean existing duplicate contracts and insert updated real contracts
        DB::table('contract_installments')->delete();
        DB::table('branch_contracts')->delete();

        foreach ($contractsData as $c) {
            $createdContract = BranchContract::create($c);

            // If it is a rented contract with rent_amount > 0, generate real historical installment records
            if ($createdContract->rent_amount > 0) {
                $installmentMonthly = $createdContract->installment_amount ?: ($createdContract->rent_amount / 12);
                $startDate = Carbon::parse($createdContract->start_date);
                $monthsElapsed = min($createdContract->duration_months, $startDate->diffInMonths(Carbon::now()) + 1);

                $paidRemaining = $createdContract->paid_value;
                for ($m = 1; $m <= $monthsElapsed; $m++) {
                    $dueDate = $startDate->copy()->addMonths($m - 1)->day($createdContract->due_day);
                    $installmentAmount = $installmentMonthly;
                    $isPaid = $paidRemaining >= $installmentAmount;
                    $paidForThis = $isPaid ? $installmentAmount : max(0, $paidRemaining);
                    $paidRemaining = max(0, $paidRemaining - $installmentAmount);

                    ContractInstallment::create([
                        'contract_id' => $createdContract->id,
                        'installment_number' => $m,
                        'due_date' => $dueDate->toDateString(),
                        'amount' => $installmentAmount,
                        'paid_amount' => $paidForThis,
                        'paid_at' => $isPaid ? $dueDate->copy()->addDays(2)->toDateString() : null,
                        'payment_status' => $isPaid ? 'PAID' : ($paidForThis > 0 ? 'PARTIAL' : ($dueDate->isPast() ? 'OVERDUE' : 'PENDING')),
                        'payment_reference' => $isPaid ? 'TRX-CHQ-' . date('Y') . '-' . rand(1000, 9999) : null,
                        'notes' => "دفعة إيجار الشهر رقم ({$m}) - " . $dueDate->translatedFormat('F Y'),
                    ]);
                }
            }
        }
    }
}
